# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_instructions', models.TextField()),
                ('event_review', models.IntegerField(default=1)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('created_update', models.DateTimeField(auto_now_add=True)),
                ('created_now', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pastevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describetion', models.CharField(max_length=1000)),
                ('event_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_playground', models.CharField(max_length=20)),
                ('descition_playground', models.CharField(max_length=50)),
                ('kind_of_sport', models.CharField(default=False, max_length=100)),
                ('Location_playground', models.CharField(max_length=10)),
                ('review_playground', models.IntegerField(default=1)),
                ('created_update', models.DateTimeField(auto_now_add=True)),
                ('created_now', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pastevent',
            name='playground',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.Playground'),
        ),
        migrations.AddField(
            model_name='event',
            name='playground',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.Playground'),
        ),
    ]
